### ISSUE TITLE
Bayesmodels Roadmap

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [AlbertoAlmuinha/bayesmodels#1]
# Bayesmodels Project Roadmap

- [x] Create Package Structure
- [x] Develop MVP Algorithms - (Sarima, Garch, Random Walk, GAM...)
- [x] Create dials parameters for tuning 
- [x] Create Tests
- [x] Automate Tests with Github Actions
- [x] Make README
- [x] Make Modeltime Integration Vignette
- [x] Pkgdown Documentation
- [x] Send to CRAN         

# Future Work

- [ ] Add more models
