### ISSUE TITLE
Bayesmodels Models Roadmap

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [AlbertoAlmuinha/bayesmodels#2]
# Actual Models

- [x] Sarima: `bayesforecast` package
- [x] Garch: `bayesforecast` package
- [x] Random Walk (Naive):  `bayesforecast` package
- [x] Stochastic Volatility:  `bayesforecast` package
- [x] State Space Model:  `bayesforecast` package
- [x] Adaptive Spline Surface: `BASS` package
- [x] GAMs: `brms` package
- [x] Structural Time Series (State Space Models): `bsts` package
- [x] Exponential Smoothing: `Rlgt` package  

# Future Models

- [ ] Additive Regression Trees: `BART` package  (no rJava dependencies)
